name: Build Android APK

push: branches: [ "main" ]

workflow dispatch:

jobs: build:

steps:

ubuntu-latest

name: Checkout code

uses: actions/checkout@v4

name: Set up JDK 17

uses: actions/setup-javav4

with:

java-version: '17'

distribution: 'temurin'

name: Find and setup gradlew

run: find -name "gradlew" -exec chnod + || true

name: Generate dunny debug keystore

run: keytool genkey -v-keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000-dname "C-US, O-Android, CN-Android Debug"

name: Build Debug APK

if [ -f "gradlew" ]; then

./gradlew assenbleDebug

elif [ -d "android" ] && [ -f "android/gradlew" ]; then

cd android &&./gradlew assembleDebug

else

fi gradle assembleDebug

name: Upload all APKS

uses: actions/upload-artifact@v4

with:

name: my-android-app

path: **/*.apk
